version: "3.5"
services:
  kanastra-upload-backend:
    container_name: kanastra-upload-backend
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      # Change on the .env file on the root of the project
      - ${APP_PORT}:80
    volumes:
      - ../:/home/app
    networks:
      - kanastra_network
networks:
  kanastra_network:
    driver: bridge
