CREATE TABLE IF NOT EXISTS fileImport (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(50),
  status VARCHAR(20) NOT NULL,
  createdAt INT DEFAULT CURRENT_TIMESTAMP,
  updatedAt INT DEFAULT CURRENT_TIMESTAMP
)